### ISSUE TITLE
Privly Button doesn't work with TinyMCE

### ISSUE THREAD

**Issue by SummerWish** [privly/privly-chrome#104]
Might be caused by `about:blank` iframe.
(Google tells me even `<all_urls>` cannot match `about:blank`)

**Comment by irdan** [comment]
I'm not sure I follow.  Please provide steps to reproduce the error.

**Comment by SummerWish** [comment]
@irdan http://www.tinymce.com/ Privly button doesn't show

**Comment by irdan** [comment]
@SummerWish Thanks for the context.

In the future try make the issues you create meaningful to anyone who reads just the issue in isolation. For example, the title of an issue should clearly describe what doesn't work and the description should provide enough context to reproduce the problem.

**Comment by SummerWish** [comment]
@irdan Sorry for the inconvenience. I have changed title to a more precise one.

**Comment by irdan** [comment]
@SummerWish No worries.  I know how easy it is to forget details like that when you're in the zone.

**Comment by smcgregor** [comment]
WYSIWYGs are the _worst_. I suppose it is good to have an issue open for it, but I am not prepared to work out the issues with how a WYSIWYG would hold the link in its state.

This would be an interesting (although not central) test case for a Seamless Posting project, but for now, I think this is a "won't fix" because it is not worth the time investment.

**Comment by SummerWish** [comment]
Found a interesting property of `manifest.json`: `match_about_blank`, which solves this issue LOL, at least in TinyMCE.

**Comment by smcgregor** [comment]
Oh, wow. TinyMCE uses srcdoc iframes.

I wonder why they lumped `about:blank` with `about:srcdoc`. Any errors in the browser or the page's console when you open a new tab?

**Comment by SummerWish** [comment]
no errors. In fact the URL of new tab is `chrome-search://local-ntp/local-ntp.html` :-)

**Comment by smcgregor** [comment]
huh. I get "https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8". Regardless, my concern was unwarranted.

**Comment by SummerWish** [comment]
The code should work for completely empty `about:blank`.
BTW the your NTP URL is interesting :-) On my Chrome it shows the new tab page but immediately jumps to Google

**Comment by SummerWish** [comment]
This patch fixes CKEditor compatibility as well. As long as it is compatible with TinyMCE and CKEditor, it should cover most of WYSIWYG use cases for normal websites.

A still-not-working example: http://ueditor.baidu.com/website/onlinedemo.html (I'm still figuring out the real issue here)

Those emulated-editing cases are still not supported: http://www.alohaeditor.org/demo/aloha-ui/

**Comment by smcgregor** [comment]
@SummerWish Is this still not working? It is difficult for me to know what is happening on the example.

**Comment by SummerWish** [comment]
@smcgregor Latest seamless-posting works in ueditor now. It is due to incorrectly handle `designMode` property and DOM hierarchy in former versions of Privly button. Emulated-editing is still not supported.

**Comment by smcgregor** [comment]
The "latest" version of seamless-posting is the one on gsoc-develop?

**Comment by SummerWish** [comment]
Yes :-)

**Comment by SummerWish** [comment]
OK I think its time to close this issue :-)
