### ISSUE TITLE
no file as chromeOptions.html

### ISSUE THREAD

**Issue by nendhruv** [privly/privly-chrome#106]
manifest file contains an options_page but there is none present in the directory.

**Comment by smcgregor** [comment]
The options page is in a git submodule. Did you do `git clone --recursive ...`?

**Comment by nendhruv** [comment]
oops sorry . my bad

**Comment by smcgregor** [comment]
No worries.

Just in case you need it: https://priv.ly/pages/develop

**Comment by nendhruv** [comment]
I read this, managed to skip the --recursive. Thanks.
