### ISSUE TITLE
Privly posting doesn't work with Youtube comment

### ISSUE THREAD

**Issue by SummerWish** [privly/privly-chrome#112]
I think it is because Youtube comment box will be destroyed once it lose focus without any content.

**Comment by irdan** [comment]
Can you provide a link to an example?

**Comment by SummerWish** [comment]
![privly-issue-youtube](https://cloud.githubusercontent.com/assets/1916485/6773047/b932d1e0-d145-11e4-998f-636d3487211c.gif)

**Comment by irdan** [comment]
Great! Thanks for the very clear example.  Do you know if there are any messages in the console when insertion of the link fails?

**Comment by SummerWish** [comment]
Sorry there are no error messages in the console.
I found that when clicking the privly button, the commentbox is closed. When opening commentbox again, the original DOM has been destroyed (it creates a new DOM for user to input comments).

**Comment by smcgregor** [comment]
Thanks for the bug report. While I don't think YouTube comments are necessarily our target use case, we certainly don't want it to break like this.

Without testing this myself, I would say @SummerWish has characterized this properly. When you click on the form element on YouTube, Google's JS creates the real form element. If the form element loses focus when it does not have any contents, Google's JS destroys the form. This is likely going to become a common web development approach over time.

Options for solving:

* Record click events and an xpath to the real form element when posting initiates. When posting completes, fire the click event again and select the proper form element with the xpath.
* Ensure there is placeholder text before opening the posting window. Replace the placeholder text when posting completes or the posting window closes.
* Others. I will think about it.

**Comment by SummerWish** [comment]
Hello. I implemented a pretty hacking solution for this issue. It works for Youtube but I have not yet tested edge cases. Please help review at this solution.

**Comment by smcgregor** [comment]
I just briefly read through your commit. Preventing the element from losing focus should be good in most cases. The only edge case I see is when the user doesn't complete posting and they navigate around the host page before returning to the posting application.

**Comment by SummerWish** [comment]
@smcgregor Yeah, thank you for the idea. Currently no workarounds for this.

**Comment by smcgregor** [comment]
I think the posting window closes at the moment regardless of whether it can successfully paste the link to the host page. If we fix #113, then the big UX problem with YouTube will be fixed.

**Comment by SummerWish** [comment]
seamless-posting works in Youtube comment, issue closed.
