### ISSUE TITLE
Privly should not try to process URLs inside editable iframe

### ISSUE THREAD

**Issue by SummerWish** [privly/privly-chrome#119]
For example, in TinyMCE, it causes extra attributes in source code.

![screen shot 2015-04-25 at 9 22 44 am](https://cloud.githubusercontent.com/assets/1916485/7330911/ab8634c8-eb2c-11e4-8a4e-4b4365a9c304.png)

 `privly.js` doesn't deal with `body[contentEditable]` correctly. #104 exposes this issue.

**Comment by SummerWish** [comment]
More precisely, `privly.js/createLinks` should not linkify links in contentEditable.

**Comment by smcgregor** [comment]
Fixed in development branch: https://github.com/privly/privly-chrome/commit/de01649c96d76827fcb6512673206597a995e7d3
