### ISSUE TITLE
Draw Attention to Extension Popup Icon on Installation

### ISSUE THREAD

**Issue by smcgregor** [privly/privly-chrome#86]
In Think-aloud studies users are not noticing the extension's icon after installing the extension. On first-run we should somehow flash the icon so the user will look at it and know they can now click there.

![screen shot 2015-02-27 at 4 22 30 pm](https://cloud.githubusercontent.com/assets/64780/6423716/eeec7836-be9e-11e4-9833-ad6887ce4cc4.png)

**Comment by irdan** [comment]
Issue https://github.com/privly/privly-chrome/issues/88 should be addressed before this issue to prevent refactoring more code than is necessary.

**Comment by suryatech** [comment]
@irdan @smcgregor When you install the extension from the Web Store, Chrome takes care of highlighting/drawing attention to the popup icon. I re-installed my extension and verified the same.

However, Chrome won't do that if you manually install the extension using the "Load unpacked extension" feature.

Ref: https://code.google.com/p/chromium/issues/detail?id=30491

**Comment by smcgregor** [comment]
What did it do to draw attention to the icon? I have never seen this.

**Comment by suryatech** [comment]
![privly added to chrome](https://cloud.githubusercontent.com/assets/6257686/6499946/a1680d3e-c329-11e4-82f9-1bc356714a82.png)

This is what I see when I install it from the chrome web store.

I am not sure about the internal working of this functionality but it has been around for a while.

And there is nothing we can do to draw attention in a programmatic fashion.

**Comment by irdan** [comment]
@smcgregor FWIW, during the most recent think-aloud that I watched I recall seeing this popup.  They still managed to miss it.  Perhaps we can hook onto the [onInstalled](https://developer.chrome.com/extensions/management#event-onInstalled) event to make sure the pop up does not go away until clicked.  In any case, it's worth reviewing the think-aloud to see exactly where this went wrong.

**Comment by smcgregor** [comment]
Thanks @suryatech!

I just re-watched the think-aloud, I think I was typing notes at this point in the video because I totally missed this. I think it would be difficult to do better than this native popup, so I am closing this. We may need to think harder about this if other think-alouds show that people miss this.
