### ISSUE TITLE
Remove LocalStorage on Uninstall

### ISSUE THREAD

**Issue by foxichu** [privly/privly-chrome#87]
I believe the LocalStorage remains in the Chrome browser even after the extension is uninstalled. Since the extension is storing keys now, this is potentially a way to compromise a key store after the user believes their keys were destroyed.

Maybe there are hooks to clear storage on extension removal?

**Comment by irdan** [comment]
Currently there is [no way](https://developer.chrome.com/extensions/faq#faq-lifecycle-events) to clear LocalStorage on uninstall of the application.  This issue is stalled until this ability is added.

**Comment by suryatech** [comment]
http://stackoverflow.com/questions/11751536/uninstalling-chrome-extension-and-associated-localstorage

Verified this on my machine. You don't have to worry about the LocalStorage of the chrome extension once it is uninstalled.

Hope this helps.

**Comment by smcgregor** [comment]
@suryatech Thanks for challenging our assumptions, I'll confirm myself and close as appropriate.

**Comment by irdan** [comment]
I set a LocalStorage value manually and then uninstalled the chrome extension.  On re-installing the extension the value I added was not present.  

While it appears we incorrectly attributed the problem, I think we need to open a new issue because I did not get the first-run page on install.

**Comment by suryatech** [comment]
@irdan I will trigger the first-run page using the on Installed event provided by chrome API. 

That should solve all existing issues related to LocalStorage and first-run page.
