### ISSUE TITLE
Use the chrome.runtime api onInstalled event to launch the firstrun page

### ISSUE THREAD

**Issue by irdan** [privly/privly-chrome#88]
There is an [event](https://developer.chrome.com/extensions/runtime#event-onInstalled) provided by the chrome.runtime api to determine when an extension is updated or installed.  Currently we use stored values in LocalStorage to determine this.  We should update [firstrun.js](https://github.com/privly/privly-chrome/blob/master/javascripts/background_scripts/first_run.js) to use this API instead of maintaining this functionality ourselves.

**Comment by suryatech** [comment]
Working on this.

**Comment by nendhruv** [comment]
PR sent on [#109](hhttps://github.com/privly/privly-chrome/pull/109)

**Comment by nendhruv** [comment]
Had some issues with #109 . Sent a new PR on #110 .

**Comment by smcgregor** [comment]
See https://github.com/privly/privly-chrome/blob/develop/javascripts/background_scripts/first_run.js#L10
