### ISSUE TITLE
Privly button weird behaiour

### ISSUE THREAD

**Issue by fullvlad** [privly/privly-chrome#90]
The following circumstances make the privly button act very strange:

- [ ] In Facebook chat small window, when the button appears in the form, if the main page is scrolled, the button will change its position according to the scrolling [1]
![GitHub Logo](http://i.imgur.com/RQEelOA.png)

- [ ] In Gmail, when composing a new mail, adding bold text and selecting it will modify the button's position [2]
![GitHub Logo](http://i.imgur.com/tw1PJS7.png)

**Comment by smcgregor** [comment]
Closing this since the gsoc-develop branch takes care of these issues.
